

--CREATE TABLE DEPARTMENT(
--	ID INT CONSTRAINT PK_DEPARMENT_ID PRIMARY KEY IDENTITY(1,1),
--	DCODE VARCHAR(10) CONSTRAINT UQ_DEPARTMENT_DCODE UNIQUE NOT NULL,
--	DNAME VARCHAR(30) INDEX IX_DEPARTMENT_DNAME NONCLUSTERED (DNAME)
--);


--INSERT INTO DEPARTMENT 
--VALUES
--('D1','MUHASEBE');

--INSERT INTO DEPARTMENT
--VALUES ('D2','BÝLGÝ ÝÞLEM'),
--	   ('D3','ÝNSAN KAYNAKLARI');


--INSERT INTO DEPARTMENT(DNAME,DCODE) VALUES ('ARGE','D4');


--UPDATE DEPARTMENT SET DNAME = 'AR-GE' WHERE DNAME = 'ARGE';

--UPDATE DEPARTMENT SET DNAME = 'AR-GE' WHERE DNAME LIKE 'AR%';  -- ADI AR ILE BASLAYAN KAYITLARI GUNCELLER.


SELECT * FROM DEPARTMENT;