
-- SYSTEM FUNC.

-- VERÝ TABANLARINDA FONKSÝYONLAR SELECT ÝLE KULLANILIR.

-- RAND: 0-1 ARASINDA RASTGELE SAYI ÜRETÜR.

SELECT RAND() AS SONUC;

-- RAND() * (MAX - MIN) + MIN;

-- 15 ÝLE 20 ARASINDA DEÐER ÜRETME
SELECT RAND()*(15 - 20) + 20;

-- MAAS ÝÇÝN 20.000 ÝLE 150.000 ARASINDA SAYI ÜRETME:

DECLARE @RND REAL;
SELECT @RND = RAND()*(150000 - 20000) + 20000; -- RND ATAMA

SELECT @RND AS SONUC, ROUND(@RND,0) AS ROUNDILE; -- ROUND , DEN SONRA KAÇ BASAMAK OLMASI GEREKTÝÐÝNÝ BELÝRLER.



SELECT 55.7845 AS SONUC, ROUND(55.7845,2) AS ROUNDKULLNIMI,
						 FLOOR(55.7845) AS FLOORKULLNIMI, -- KUCUK SAYIYA YUVARLAR
						 CEILING(55.7845) AS CEILINGKULLNIMI; -- BUYUK SAYIYA YUVARLAR

