
-- CAST VE CONVERT FONKSIYONLARI
DECLARE @MAAS REAL,@YAS INT;

SELECT @MAAS = 72455.88,@YAS = 22;

PRINT 'KIÞÝNÝN MAAÞI: ' + CONVERT(VARCHAR(20),@MAAS) + ' ' + 'YAS: '+ CAST(@YAS AS VARCHAR);
