-- T-SQL: MICROSOFT TARAFINDAN INSA EDILMIS GELISMIS BIR DIL. MS-SQL'DE KULLANILIYOR.

-- PL-SQL: WHILE IF FOR GIBI SEYLER VARDIR. ORACLE VE POSTGRE SQL DE KULLANILMAKTA.

-- DEÐÝÞKEN TANIMLAMAK ÝÇÝN DECLARE KULLANILIR.
-- BÝR DEÐÝÞKEN BÝLDÝRÝMÝ @ ÝFADESÝ ÝLE BAÞLAR.
-- SÝSTEM DEÐÝÞKENLERÝ @@ ÝLE BAÞLAR.
-- CONSOLA MESAJ YAZDIRMAK: PRINT()
-- DEÐÝÞKENLERE DEÐER ATAMAK ÝÇÝN:
-- 1-) SET ÝFADESÝ (TEK DEÐÝÞKEN)
-- 2-) SELECT ÝFADESÝ (TEK VEYA DAHA FAZLA DEÐÝÞKEN)

DECLARE @A INT, 
		@B FLOAT, 
		@AD VARCHAR(20), 
		@SOYAD VARCHAR(20),
		@ADSOYAD VARCHAR(40), 
		@DTARIHI DATE, 
		@MASSI DECIMAL(10,2), 
		@CINSIYET CHAR(1);

SELECT * FROM Employees; -- ÇALIÞANLAR
SELECT * FROM Customers; -- MÜÞTERÝLER
SELECT * FROM Orders;    -- SÝPARÝÞLER
SELECT * FROM [Order Details];    -- SÝPARÝÞ DETAY
SELECT * FROM Shippers;  -- NAKLÝYAT
	

-- ÇALIÞAN TABLOSUNA MAAÞ SÜTUNUNUN EKLENMESÝ

--ALTER TABLE EMPLOYEES 
--ADD SALARY DECIMAL(10,3) NOT NULL DEFAULT(0);




